no change     /gpfs/users/a1796450/anaconda3/condabin/conda
no change     /gpfs/users/a1796450/anaconda3/bin/conda
no change     /gpfs/users/a1796450/anaconda3/bin/conda-env
no change     /gpfs/users/a1796450/anaconda3/bin/activate
no change     /gpfs/users/a1796450/anaconda3/bin/deactivate
no change     /gpfs/users/a1796450/anaconda3/etc/profile.d/conda.sh
no change     /gpfs/users/a1796450/anaconda3/etc/fish/conf.d/conda.fish
no change     /gpfs/users/a1796450/anaconda3/shell/condabin/Conda.psm1
no change     /gpfs/users/a1796450/anaconda3/shell/condabin/conda-hook.ps1
no change     /gpfs/users/a1796450/anaconda3/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /gpfs/users/a1796450/anaconda3/etc/profile.d/conda.csh
no change     /gpfs/users/a1796450/.bashrc
No action taken.

CondaError: Run 'conda init' before 'conda activate'

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:03<00:06,  3.36s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:06<00:03,  3.47s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:10<00:00,  3.35s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:10<00:00,  3.37s/it]
We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)
